### ISSUE TITLE
Movement of insect is behaving strangely when rotating and walking at once

### ISSUE THREAD

**Issue by guemax** [guemax/GameOff2021#1]
**Describe the bug**
Controlling the bug/insect is behaving very strangely, expecially when rotating it: When I press the up arrow first and either the left or the right arrow key, the insect walks forward and rotates.

However, when I first press either the left or the right arrow key (the insect starts rotating) and then the up arrow key, the insect walks forward but stops rotating.

**To Reproduce**
1. Open the project in Godot
2. Run the project
3. Press the left/right arrow key first and then the up arrow key
4. The insect stops rotating as soon as you press the up arrow key.

**Expected behavior**
In my opinion, first pressing the left/right arrow key and then pressing the up arrow key should result in the insect moving forward **and** rotating either left or right at the same time.

**Desktop:**
 - OS: Windows
 - Version 10

https://user-images.githubusercontent.com/93522160/141326510-b607edc2-a7b6-415c-acb6-571600070e78.mp4

In the video above I recorded myself playing the game:
First I press the up arrow key and afterwards the left arrow and the right arrow key. I then release all keys and press the left arrow key and the up arrow key. You can see how the bug starts rotating left and stop rotating when the insect walks forwards. I did the same thing with first pressing the right arrow key and then pressing the up arrow key.

**Comment by guemax** [comment]
Fixed with commit 745122152a8a1db85f7ad4373be1b53fb84b76e0

**Comment by PingGames** [comment]
There is a bug in the game! :-)
